{
 "title": "pgreplay-go",
 "description": "Benchmarking dashboard for https://github.com/gocardless/pgreplay-go",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,15m" },
   {
    "name": "podName",
    "query": {
     "query": "label_values({namespace=\"pgreplay\"},pod)"
    }
   },
   { "name": "loki_source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Items Processed/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pgreplay_items_processed_total{pod=\"$podName\"}[$interval])",
     "legendFormat": "items/s"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgreplay_connections_active{pod=\"$podName\"}",
     "legendFormat": "active"
    },
    {
     "expr": "rate(pgreplay_connections_established_total{pod=\"$podName\"}[$interval])",
     "legendFormat": "established/s"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1.0 - pgreplay_items_filter_progress_fraction{pod=\"$podName\"}) / rate(pgreplay_items_filter_progress_fraction{pod=\"$podName\"}[$interval]), 0)"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgreplay_items_filter_progress_fraction{pod=\"$podName\"}"
    }
   ]
  },
  {
   "title": "Go Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{pod=\"$podName\"}\nand\npgreplay_connections_active{pod=\"$podName\"}",
     "legendFormat": "heap bytes"
    },
    {
     "expr": "go_goroutines{pod=\"$podName\"}\nand\npgreplay_connections_active{pod=\"$podName\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{pod=\"$podName\"} |= ``"
    }
   ]
  }
 ]
}